username = "vagrant"
password = "vagrant"
connection_method = "password"
hosts = [
        "192.168.11.101",
        "192.168.11.102",
        "192.168.11.103"
]
commands_file = "/home/zrad/commands"
